platform:ios,'7.0'

pod 'AFNetworking', '~> 3.0.4'
pod 'YYModel', '~> 1.0.1'
pod 'PureLayout', '~> 3.0.1'
pod 'KDCycleBannerView', '1.1.1'
pod 'Toast', '2.4'
pod 'FMDB', '2.5'
pod 'MBProgressHUD', '0.9.1'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '3.7.2'
pod 'UMengMessage-NO-IDFA', '~> 1.2.3'
pod 'UIAlertView-Blocks', '~> 1.0'
